name: Empowering IT
favicon: null
layout_spectrum: 0.5486455727368593
typography_spectrum: 0.8550712277647108
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.08847304107621312
  lightness: 0.6741028560791165
  saturation: 0.26541811344213784
  rhythmicContrast: 0.38183140428736806
purpose: []
